### ISSUE TITLE
How to create mutilple custom elements?

### ISSUE THREAD

**Issue by adsl99801** [bpmn-io/bpmn-js-example-custom-elements#2]
If I want to create two or more element (step1 ,step2)
How to do?
I geuess:
copy second  emoji.json to step1.json step2.json
in modify EmojiRenderer.js
```
EmojiRenderer.prototype.canRender = function(element) {
  if (!is(element, 'bpmn:Task')) {
    return;
  }

  var businessObject = getBusinessObject(element);

  return businessObject.emoji;
};
```
return businessObject.emoji;// bool  or String?
I'm confuse.

I don’t know what is alone file and what can reused.

**Comment by philippfromme** [comment]
`emoji.json` defines a model extension. You can specify as many custom attributes and elements in it as you want. Have a look at this example: https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-meta-model

For any requests that are not a bug/feature request please use the [forum](https://forum.bpmn.io/).
